# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opqpwd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UidSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuidset', models.TextField(max_length=87640, validators=[django.core.validators.RegexValidator(message='Expecting Base64 string', regex='^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'), django.core.validators.RegexValidator(message='length has to be 87640', regex='^.{87640}$')])),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uidset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'encuidset'),
            },
        ),
        migrations.AlterModelOptions(
            name='usercred',
            options={'ordering': ('husername', 'hpassword', 'hpassword_salt')},
        ),
        migrations.RemoveField(
            model_name='usercred',
            name='encuidset',
        ),
        migrations.AlterField(
            model_name='usercred',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usercred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uidset',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opqpwd.UserCred'),
        ),
    ]
