# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opqpwd', '0002_auto_20161105_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uidset',
            options={},
        ),
        migrations.RemoveField(
            model_name='uidset',
            name='user',
        ),
    ]
