# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opqpwd', '0003_auto_20161105_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passworddata',
            name='encdata',
            field=models.TextField(max_length=1964, validators=[django.core.validators.RegexValidator(message='Expecting Base64 string', regex='^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'), django.core.validators.RegexValidator(message='length has to be 1964', regex='^.{1964}$')]),
        ),
    ]
