# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opqpwd', '0005_auto_20161111_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uidset',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uidset', to=settings.AUTH_USER_MODEL),
        ),
    ]
