# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opqpwd', '0007_auto_20161115_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='encpasslist',
            field=models.TextField(max_length=266924, validators=[django.core.validators.RegexValidator(message='Expecting Base64 string', regex='^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'), django.core.validators.RegexValidator(message='length has to be 266924', regex='^.{266924}$')]),
        ),
    ]
